name: 16 - Working with Environments
run-name: 16 - Working with Environments | env - ${{ inputs.target_environment }}
on:
  workflow_dispatch:
    inputs:
      target_environment:
        type: environment
        default: staging
        description: Input for the target environment

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }}
    env:
      MY_ENV_VALUE: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      - name: Echo vars
        run: echo Env variable $MY_ENV_VALUE