name: "Testing concurency for the workflows within one group"
on:
  push:
    branches: [main]
#concurrency:
#  group: 'my-concurency-group'
#  cancel-in-progress: true

jobs:

  cjob:
    runs-on: ubuntu-latest
    steps:

      - name: "A test step into the job in concurrent workflow"
        run: echo something

  calling_another_workflow:
    uses: Karatonev/called_workflows/.github/workflows/called_workflow.yml@main
    with:
      input1: hristo

  display_output_from_called_workflow:
    needs: calling_another_workflow
    runs-on: ubuntu-latest
    steps:

      - name: step1
        run: echo "${{needs.calling_another_workflow.outputs.secret_called_repo}}"

  docker-action:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: |
          node --version
          npm --version