name: "Testing concurency for the workflows within one group"
on:
  push:
    branches: [main]
#concurrency:
#  group: 'my-concurency-group'
#  cancel-in-progress: true

jobs:

  cjob:
    runs-on: ubuntu-latest
    steps:

      - name: "A test step into the job in concurrent workflow"
        run: echo something

  calling_another_workflow:
    uses: Karatonev/called_workflows/.github/workflows/called_workflow.yml@main
    with:
      input1: hristo
    #secrets: inherit

  display_output_from_called_workflow:
    needs: calling_another_workflow
    runs-on: ubuntu-latest
    steps:

      - name: step1
        run: echo "${{needs.calling_another_workflow.outputs.secret_called_repo}}"

  docker-action:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: |
          node --version
          npm --version

  job1:
    runs-on: ubuntu-latest
    concurrency:
      group: group1
    steps:
      - name: step1
        run: echo "This is a step1 in job1"

      - name: step2
        run: echo "This is a step2 in job1"

  job2:
    runs-on: ubuntu-latest
    concurrency:
      group: group1

    steps:
      - name: step1
        run: echo "This is a step1 in job2"

      - name: step2
        run: echo "This is a step2 in job2"

  job3:
    runs-on: ubuntu-latest
    concurrency:
      group: group1

    steps:
      - name: step1
        run: echo "This is a step1 in job3"

      - name: step2
        run: echo "This is a step2 in job3"
