name: "Testing concurency for the workflows within one group"
on:
  push:
    branches: [main]
#concurrency:
#  group: 'my-concurency-group'
#  cancel-in-progress: true

jobs:

  cjob:
    runs-on: ubuntu-latest
    steps:

      - name: "A test step into the job in concurrent workflow"
        run: echo something

  calling_another_workflow:
    uses: Karatonev/called_workflows/.github/workflows/called_workflow.yml

  docker-action:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: |
          node --version
          npm --version