name: 'Build and deploy static website using AWS S3 as a backend'
run-name: '${{ github.actor }} deploying static web site using custom JS action'
on:
  push:
    branches: [main]
    tags: [T4]

jobs:
  DisplayInfo:
    runs-on: ubuntu-latest
    steps:
      - name: 'Display test information'
        run: "echo ${{ github.actor }} is doing something on REF=${{ github.ref }} TYPE=${{ github.ref_type }}"
  InformationfromCustomAction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 'Run Custom Action'
        uses: ./.github/actions/javascript

      - name: 'Display messages in groups'
        run: |
           echo "::group::Process"
           echo "Starting"
           echo "Cleaning Up"
           echo "::endgroup::"

      - name: 'Try to display the token'
        run: |
          echo "${{ github.token }}"
          echo "${{ secrets.GITHUB_TOKEN }}"
  MatrixTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1,2,3]
        os: [linux, windows]
    steps:
      - name: "Display ${{ matrix.version }} and ${{ matrix.os }}"
        run: echo "${{ matrix.version }} and ${{ matrix.os }}"
