name: 'This is a workflow that is triggered by the workflow_dispatch event and utilize inputs'
on:
  workflow_dispatch:
    inputs:
      log_level:
        description: "Choose the verbosity of the logs"
        type: choice
        options:
          - info
          - warning
          - debug
        required: true

      tag:
        description: "A tag that could be used"
        type: string
        required: true
        default: "test"

jobs:
  display_inputs:
    runs-on: ubuntu-latest
    steps:

      - name: Display the actual input
        run: echo  ${{ inputs.log_level }}

      - name: Display the actual input for tag
        run: echo "the chosen tag is ${{ inputs.tag }}"