name: This is a worklow which is utilizing custom docker action
run-name: ${{ github.actor }} is executing ${{ github.workflow }} on ${{ github.ref_name }}
on:
  workflow_dispatch:
    permissions: write
    inputs:
      aws_region:
        type: string
        default: eu-west-1
        description: AWS Region for delpoyment

      bucket_name:
        type: S3 Bucket Name
        description: The name of the S3 Bucket to be created.

jobs:
  invoke_custom_docker_action:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4


      - name: Actual run
        id: docker
        uses: ./.github/actions/docker-test

      - name: Display the output from docker action
        run: echo ${{ steps.docker.outputs.DOCKER_OUTPUT_01 }}


