name: Trigger by a pull request
on:
  pull_request_target:
    types:
      - opened
    branches:
      - main
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: PR Information
        run: echo "${{ github.event.number }}"

      - name: Add Label to the PR
        run: gh pr edit ${{ github.event.number }} --add-label "prlabel"