name: "A workflow that should be triggered by the completion of another workflow"
on:
  workflow_run:
    workflows: ["Build and deploy static website using AWS S3 as a backend"]
    types:
      - completed
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:

      - name: Display Something
        run: echo "Success"

      - name: Set output for a job
        run: echo "test_job_output=test_job_output_value">> $GITHUB_OUTPUT


  new_job:
    runs-on: ubuntu-latest
    needs: test_job
    steps:

      - name: Display the output from another job
        run: echo ${{ needs.test_job.outputs.test_job_output }}