name: Pure informational workflow
on:
  push:
jobs:
    information:
      runs-on: ubuntu-latest
      steps:
        - name: Workflow name
          run: echo "${{ github.workflow }}"

        - name: Github SHA
          run: echo "${{ github.sha }}"

        - name: Display SHA using default environment variable
          run: echo $GITHUB_WORKFLOW_SHA

        - name: Github Event Name
          run: echo "${{ github.event_name }}"